spring.application.name=poi-detector
spring.datasource.url=jdbc:postgresql://db.epfjbzothysygppdanoz.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=supabase@POIdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
server.port=${PORT:8089}