spring.application.name=poi-detector
spring.datasource.url=jdbc:postgresql://ep-hidden-glade-a17rhl99-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_b3Lwd7TkzBFs
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
server.port=${PORT:8089}